/vis/open OGLIX

/vis/geometry/list
/vis/drawVolume 
#/vis/scene/add/volume AlBase
#/vis/scene/add/volume AmSource
#/vis/scene/add/volume SiT
#/vis/scene/add/volume CollimatorPlastic
#/vis/scene/add/volume SiL3

/vis/viewer/set/style w
/vis/viewer/addCutawayPlane 0 7.5 0 cm 0 -1 0
/vis/viewer/set/viewpointThetaPhi 70 90

# Top Down
#/vis/viewer/set/viewpointThetaPhi 90 90

# Side View
#/vis/viewer/set/viewpointThetaPhi 90 0

# End On View
#/vis/viewer/set/viewpointThetaPhi 0 180
#/vis/viewer/addCutawayPlane 0 0 0 cm 0 0 -1

/vis/viewer/set/background 1 1 1 0

/vis/scene/add/axes 30 -10 30 5 cm
#/vis/scene/add/axes 20 -2.5 -20 5 cm
#/vis/scene/add/axes -5 -2.5 5 5 cm

/vis/filtering/trajectories/create/particleFilter muon
#/vis/filtering/trajectories/muon/add mu-
/vis/filtering/trajectories/muon/add e+
#/vis/filtering/trajectories/muon/add geantino
#/vis/filtering/trajectories/muon/add proton
#/vis/filtering/trajectories/muon/invert false

/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate